### ISSUE TITLE
What is the needed permission to list and download report using gvm-cli

### ISSUE THREAD

**Issue by aabuhasna** [greenbone/gvm-tools#1015]
Hi

I am using the latest version go Greenbone (all components), the issue I am facing when I use gvm-cli to get tasks is I get tasks' count 0 even when I grant the user the ability to authenticate, get_report, get_report_format, and get_task, but if I use the main admin I get the accurate result, my question how to get the result I need using a normal user and what is the needed permission for that?

The result below when I use a normal user

 gvm-cli --gmp-username=foo --gmp-password=bar socket --xml "<get_tasks/>"
<get_tasks_response status="200" status_text="OK"><apply_overrides>0</apply_overrides><filters id=""><term>apply_overrides=0 min_qod=70 first=1 rows=10 sort=name</term><keywords><keyword><column>apply_overrides</column><relation>=</relation><value>0</value></keyword><keyword><column>min_qod</column><relation>=</relation><value>70</value></keyword><keyword><column>first</column><relation>=</relation><value>1</value></keyword><keyword><column>rows</column><relation>=</relation><value>10</value></keyword><keyword><column>sort</column><relation>=</relation><value>name</value></keyword></keywords></filters><sort><field>name<order>ascending</order></field></sort><tasks start="1" max="1000"/><task_count>0<filtered>0</filtered><page>0</page></task_count></get_tasks_response>

**Comment by bjoernricks** [comment]
Hi,

this is a support question rather then a bug report. Please ask your question at https://forum.greenbone.net/ for getting help from the community.
