### ISSUE TITLE
Get rid of exec usage in scripts/send-tasks.gmp

### ISSUE THREAD

**Issue by bjoernricks** [greenbone/gvm-tools#115]
Hi @jschwartz27,

could you please refactor scripts/send-tasks.gmp to not use an exec statement? Using exec pollutes the global namespace and executing python code dynamically from a string is very dangerous. I am going to remove the script completely if we can't refactor it.

**Comment by jschwartz27** [comment]
Hi Björn,
Yes I can fix it and remove the exec statement

Joshua

**Comment by bjoernricks** [comment]
Should be fixed with #129
