### ISSUE TITLE
how to activated the GMP Protocol？

### ISSUE THREAD

**Issue by HelloXiaoHe** [greenbone/gvm-tools#17]
hi,
I successfully installed **openvas** and **gvm-tools**.

cd /usr/local/python3.6.5/bin
run 
./gvm-cli socket --gmp-username admin --gmp-password 123456 --sockpath /run/redis/redis.sock --xml "<create_target><name>Suspect Host</name><hosts>10.17.2.137</hosts></create_target>"

it return , timed out

and find the User Manuals , 
http://docs.greenbone.net/GSM-Manual/gos-4/en/omp.html#activating-the-gmp-protocol
http://docs.greenbone.net/GSM-Manual/gos-4/en/systemadministration.html#gmp

but I cant find the menu

**Comment by rgrewe** [comment]
You have used the wrong socket. Default for sockpath is "/usr/local/var/run/openvasmd.sock". You have to look where your openvasmd.sock exist.

**Comment by HelloXiaoHe** [comment]
thanks,it works,i find my openvasmd.sock
find / -name openvasmd.sock
/run/openvasmd.sock
then I try again
./gvm-cli socket --gmp-username admin --gmp-password 123456 --sockpath /run/openvasmd.sock --xml "<create_target><name>Suspect Host</name><hosts>10.17.2.137</hosts></create_target>"

it return the right response
<create_target_response status="201" status_text="OK, resource created" id="e38627b6-9ea5-48cf-bb11-79413bd2c2cb"/>

then I get the config_id
./gvm-cli socket --gmp-username admin --gmp-password 123456 --sockpath /run/openvasmd.sock --xml "<get_configs/>"
it return the config_id is e38627b6-9ea5-48cf-bb11-79413bd2c2cb
and  create the task

./gvm-cli socket --gmp-username admin --gmp-password 123456 --sockpath /run/openvasmd.sock --xml "<create_task><name>Scan Suspect Host</name><target id="8715c877-47a0-438d-98a3-27c7a6ab2196"></target><config id="e38627b6-9ea5-48cf-bb11-79413bd2c2cb"></config></create_task>"

but it return 
Connection was closed by remote server

**Comment by rgrewe** [comment]
According to http://docs.greenbone.net/API/OMP/omp-7.0.html#command_create_task and http://docs.greenbone.net/GSM-Manual/gos-4/en/omp.html#activating-the-gmp-protocol you have to add at least a target id and a config id. 

F.e.:
--xml "<create_task><name>Scan Suspect Host</name> \
<target id=\"4574473f-a5d0-494c-be6f-3205be487793\"></target> \
<config id=\"daba56c8-73ec-11df-a475-002264764cea\"></config></create_task>"

**Comment by cfi-gb** [comment]
I would suggest to move this discussion over to http://lists.wald.intevation.org/cgi-bin/mailman/listinfo/openvas-discuss as also advised in https://github.com/greenbone/openvas-scanner/issues/71

This avoids that the information here gets lost within a bugtracker and is archived within the mailinglist.

**Comment by HelloXiaoHe** [comment]
@rgrewe I make a mistake on the question,
I run this command in fact
./gvm-cli socket --gmp-username admin --gmp-password 123456 --sockpath /run/openvasmd.sock --xml "<create_target><name>Suspect Host</name><hosts>10.17.2.137</hosts></create_target>"
Is the target_id is return by <create_target> or custom? 
I get the config_id by <get_config>
it also return ,Connection was closed by remote server
is there anyelse I forget to config?

@cfi-gb hi, my English is poor,I dont know how to use the mailinglist,do you mean that I would sent the email with the discussion?
