### ISSUE TITLE
how to generate the html report

### ISSUE THREAD

**Issue by HelloXiaoHe** [greenbone/gvm-tools#18]
hi,I use the command <get_reports id="" format_id="6c248850-1f62-11e1-b082-406186ea4fc5">
but it dosent generate a file ,so I use command <get_reports id="">| tee result.xml

I find one way to generate html file,
cd /usr/share/openvas/openvasmd/report_formats/6c248850-1f62-11e1-b082-406186ea4fc5
then run ./generate ~/result.xml \>/temp/result.html
it seems work

is there  a esay way to generate the html report?

**Comment by cfi-gb** [comment]
@HelloXiaoHe As asked in other issues please ask your question by writing a mail to openvas-discuss@wald.intevation.org

**Comment by HelloXiaoHe** [comment]
@cfi-gb done

**Comment by wiegandm** [comment]
While GMP syntax is somewhat out-of-scope for `gvm-tools` and @HelloXiaoHe already asked on the mailing list as @cfi-gb suggested, it should be noted that the correct attribute for specifying a single report in the `get_reports` command is `report_id`, _not_ `id`.

So the command
  `<get_reports report_id='uuid-of-the-report' format_id='6c248850-1f62-11e1-b082-406186ea4fc5' />`
will result in a `get_reports_response` reply which contains the Base64-encoded HTML report as a text child of the `report` element.

A protocol specification of the GMP protocol is available at <http://docs.greenbone.net/API/OMP/omp-7.0.html>.
