### ISSUE TITLE
GMP credentials must be passed before connection type

### ISSUE THREAD

**Issue by wiegandm** [greenbone/gvm-tools#182]
### Expected behavior

Earlier version of `gvm-cli` used to expect the `CONNECTION_TYPE` before all
other parameters, i.e.:

```
gvm-cli ssh --gmp-username foo --gmp-password bar --xml '<get_reports/>'
```

### Current behavior

Using the sequence above, the current version of gvm-cli prints a traceback
ending with `FileNotFoundError: [Errno 2] No such file or directory: 'foo'`

Reordering the paremeters as follows make the call work again:

```
gvm-cli --gmp-username foo --gmp-password bar ssh --xml '<get_reports/>'
```

### Steps to reproduce

See above in *Expected behavior*.

### GVM versions
**gvm-tools:** (gvm-cli --version)

`gvm-cli 2.0.0b1 (API version 1.0.0b2.dev1)`

**Comment by bjoernricks** [comment]
@wiegandm this issue is nearly impossible to fix with argparse :disappointed:

I am thinking about switching to [click](https://click.palletsprojects.com) or dropping the support for
`gvm-cli ssh --gmp-username foo --gmp-password bar`.
