### ISSUE TITLE
[2.0.0] Exception errors are not catched clearly

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gvm-tools#221]
Very often I see python exception using the gvm-cli tool.
Every uncatched exception will trigger an new abrt event.
For example:

> sudo -u gvmd gvm-cli socket --socketpath /var/run/greenbone/ospd-openvas.sock --xml "<help/>"
> Traceback (most recent call last):
>   File "/bin/gvm-cli", line 11, in <module>
>     load_entry_point('gvm-tools==2.0.0', 'console_scripts', 'gvm-cli')()
>   File "/usr/lib/python3.6/site-packages/gvmtools/cli.py", line 127, in main
>     with protocol_class(connection, transform=transform) as protocol:
>   File "/usr/lib/python3.6/site-packages/gvm/protocols/gmp.py", line 78, in __enter__
>     self.connect()
>   File "/usr/lib/python3.6/site-packages/gvm/protocols/base.py", line 107, in connect
>     self._connection.connect()
>   File "/usr/lib/python3.6/site-packages/gvm/connections.py", line 349, in connect
>     self._socket.connect(self.path)
> PermissionError: [Errno 13] Permission denied
> 
The will flood the system abrt log/stack.
It will be much better, when the exception of the gvm python library are catched and printed out as an error message.

**Comment by bjoernricks** [comment]
Fixed with #224
