### ISSUE TITLE
Issues with gmp.create_target alive_test parameter

### ISSUE THREAD

**Issue by Devilxpto** [greenbone/gvm-tools#243]
I'm having an issue trying to set the "Consider Alive" when creating a target through Python API:

target = gmp.create_target(f"{target_ip}_target", hosts=[target_ip], port_range=target_ports, alive_test="Consider Alive")

I get:

gvm.errors.InvalidArgument: Invalid argument alive_test for create_target

Any ideas ?

**Comment by bjoernricks** [comment]
You need to pass an AliveTest enum instance. For details please take a look at the api docs

**Comment by y0urself** [comment]
This should now be fixed thanks to https://github.com/greenbone/gvm-tools/pull/297.
