### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by BasvanH** [greenbone/gvm-tools#257]
### Expected behavior
gvm-tools to be installed

### Current behavior
Are not installed via various ways

### Steps to reproduce
Install thru git clone fails, there's no setup.py in the root.
```
$cd /opt/gvm/src
$git clone https://github.com/greenbone/gvm-tools.git
$pip install -e /opt/gvm/src/gvm-tools
Directory '/opt/gvm/src/gvm-tools' is not installable. File 'setup.py' not found.
```
Install thru pip repository fails
```
$pip install gvm-tools
Collecting gvm-tools
  Could not find a version that satisfies the requirement gvm-tools (from versions: )
No matching distribution found for gvm-tools
```

**Comment by y0urself** [comment]
### With pip

Is your `pip` command linked to pip3? I have no issues installing `gvm-tools` over `pip3`:

```bash
$ pip3 install gvm-tools
Collecting gvm-tools
  Downloading gvm_tools-2.1.0-py3-none-any.whl (30 kB)
```

___

### From Github

We replaced pipenv with poetry in #246.
So I think you tried to build the master branch of this project and you will need to install it with poetry (and need to install poetry before).
See [here](https://github.com/greenbone/gvm-tools/blob/master/README.md#contributing).

**Comment by BasvanH** [comment]
Indeed, it works with `pip3`, thanks!

**Comment by bjoernricks** [comment]
btw. it is best to run `python3 -m pip install` to get rid of that nasty pip pip3 confusion.
