### ISSUE TITLE
How can I authenticate using Osp

### ISSUE THREAD

**Issue by jpalanco** [greenbone/gvm-tools#273]
When I try to run the following code:

```python
with Osp(connection, transform=transform) as osp:
    response = osp.get_version()
    pretty_print(response)

    # It doenst exists autenticate method in osp
    #osp.authenticate('admin', 'admin')

    # Display scans
    scans = osp.get_scans()
    pretty_print(scans)
```

I get this error:

<gmp_response status="400" status_text="Only commands GET_VERSION and COMMANDS are allowed before AUTHENTICATE"/>

I was able to work with Gmp, but it seems Osp only exposes get_version() because for the other functions I need to be authenticated, and there is no way for authenticate.

What I am doing wrong?

**Comment by jjnicola** [comment]
Hi @jpalanco,

It seems you are connecting to the gvmd socket, instead to the OSP socket. As this is not a bug, if you have still more questions, the right channel for asking about this is https://community.greenbone.net/c/gse.

Regards,
Juan
