### ISSUE TITLE
Feature request: alerts support / usage documentation

### ISSUE THREAD

**Issue by hacker-h** [greenbone/gvm-tools#29]
The functions

`def create_task(self, name, config_id, target_id, scanner_id, comment='')`
> gvm_tools/gmp/gvm_connection.py

and

`def createTaskCommand(self, name, config_id, target_id, scanner_id, comment='')
`
> gvm_tools/gmp/gmp.py

do not allow the usage of an alert_id or alerts in general.

Also I can not recognize regarding its code how to invoke the function
`def createAlertCommand(self, name, condition, event, method, filter_id='', copy='', comment='')`
> gvm_tools/gmp/gmp.py

respectively

`def create_alert(self, name, condition, event, method, filter_id='', copy='', comment='')`
> gvm_tools/gmp/gvm_connection.py

**Comment by bjoernricks** [comment]
API docs have been added to https://github.com/greenbone/python-gvm
