### ISSUE TITLE
scan-new-system.gmp.py sample script cause "Response Error 400. One of PORT_LIST and PORT_RANGE are required". 

### ISSUE THREAD

**Issue by omok314159** [greenbone/gvm-tools#294]
### Expected behavior
[After gmp-20.08, CREATE_TARGET will need PORT_LIST or PORT_RANGE.
](https://docs.greenbone.net/API/GMP/gmp-20.08.html#changes)
Then I can't create scan job by using it.
I modified the "scan-new-system.gmp.py" for supporting PORT_LIST_ID with argument, then it worked fine(see as below).

[patch_scan_new_system.txt](https://github.com/greenbone/gvm-tools/files/5259330/patch_scan_new_system.txt)

### Current behavior
Current scan-new-system.gmp.py does not have PORT_LIST or PORT_RANGE on the argument. 
When I ran "scan-new-system.gmp.py" with gvm-script, I have error as below;
```Response Error 400. One of PORT_LIST and PORT_RANGE are required```

### Steps to reproduce
1. run below command wit gvm user;  
```/usr/local/bin/gvm-script --gmp-username admin --gmp-password [PASS] tls --port=9390 --host=127.0.0.1 /data/gvm-tools/scripts/scan-new-system.gmp.py [HOST]```  
2. Then you'll see following error;
```
 Response Error 400. One of PORT_LIST and PORT_RANGE are required
```

### GVM versions
**gsa:** (gsad --version)
20.08.0
**gvm:** (gvmd --version)
20.08.0
**gvm-tools:** (gvm-cli --version)
gvm-cli 2.1.0 (API version 1.6.0)

### Environment
**Operating system:**
Debian buster
**Installation method / source:** (packages, source installation)
[GVM-Docker](https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker)
### Logfiles

```
 Response Error 400. One of PORT_LIST and PORT_RANGE are required
```

**Comment by y0urself** [comment]
You might want to create an Pull Request with your changes?

**Comment by omok314159** [comment]
Thanks [y0urself](https://github.com/y0urself). I create Pull Request.
(I'm not confident because this is my first time to create Pull Request.)

[https://github.com/greenbone/gvm-tools/pull/295
](https://github.com/greenbone/gvm-tools/pull/295
)

**Comment by omok314159** [comment]
[y0urself](https://github.com/y0urself), thanks to merge it.

Kind Regards,
