### ISSUE TITLE
Scan /16 ranges

### ISSUE THREAD

**Issue by arkhelieldan** [greenbone/gvm-tools#302]
I'm using the latest build, but I'm having problems with scanning in the cloud, I believe it's openvas' own, but it doesn't allow scheduling a scan or creating a list of targets with range / 16.

I have a VPC 10.10.0.0/16 and I need to scan new hosts that appear, since if I update the list with new IPs I will have to delete the schedule, the results and the current target.

Is there any way to scan with this range? I read that it is possible, but only if you make any changes to the GVMD.

### Expected behavior

Schedule / 16 range.

### Current behavior

Informs that it is not a valid entry.

**Comment by y0urself** [comment]
What command/script are you using that is related to the `gvm-tools`?

**Comment by arkhelieldan** [comment]
Hi, i`m not using script.
I read in this topic about increase scan of gvmd: https://community.greenbone.net/t/gmp-scanner/2050/22
But i dont know to use this in docker to scan /16 range.

**Comment by y0urself** [comment]
Do you think this is a bug or a missing feature to any of Greenbone's components or are you looking for the answer to an usage issue?
Maybe you can find help in the [community]( https://community.greenbone.net), you already linked?

**Comment by y0urself** [comment]
This issue is not related to gvm-tools at all.
Maybe you can try to setup our environment on your own, instead of using third party dockers.
