### ISSUE TITLE
Directory 'gvm-tools' is not installable. File 'setup.py' not found.

### ISSUE THREAD

**Issue by BhagyashreeKoyande** [greenbone/gvm-tools#329]
Hii,
 
I have installed gvm-tools using pip3. The command I used is python3 -m pip install gvm-tools.
After that I clone the github repo(https://github.com/greenbone/gvm-tools) in my home directory.
Now when I want to install gvm-tools in python environment I get an error as - "Directory 'gvm-tools' is not installable. File 'setup.py' not found.". The command I used is- python3 -m pip install -e gvm-tools
The terminal output is as follows:

**bhagyashree@bhagyashree-Inspiron-3521:~$ python3 -m pip install gvm-tools**
Collecting gvm-tools
  Using cached https://files.pythonhosted.org/packages/9f/f9/0c74766014fbe9135f8a213774a7b4e1747264a31c9ec2e9cf1bbf371fb2/gvm_tools-20.10.1-py3-none-any.whl
Collecting python-gvm<21.0,>=1.4 (from gvm-tools)
  Using cached https://files.pythonhosted.org/packages/f1/8c/6dd45402b52c5430bbfabfb18e9e58f6a40e693e8da5fe0d95cf2adc1b1c/python_gvm-20.11.0-py3-none-any.whl
Collecting paramiko<3.0.0,>=2.7.1 (from python-gvm<21.0,>=1.4->gvm-tools)
  Using cached https://files.pythonhosted.org/packages/95/19/124e9287b43e6ff3ebb9cdea3e5e8e88475a873c05ccdf8b7e20d2c4201e/paramiko-2.7.2-py2.py3-none-any.whl
Collecting defusedxml<0.7.0,>=0.6.0 (from python-gvm<21.0,>=1.4->gvm-tools)
  Using cached https://files.pythonhosted.org/packages/06/74/9b387472866358ebc08732de3da6dc48e44b0aacd2ddaa5cb85ab7e986a2/defusedxml-0.6.0-py2.py3-none-any.whl
Collecting lxml<5.0.0,>=4.5.0 (from python-gvm<21.0,>=1.4->gvm-tools)
  Using cached https://files.pythonhosted.org/packages/64/28/0b761b64ecbd63d272ed0e7a6ae6e4402fc37886b59181bfdf274424d693/lxml-4.6.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting pynacl>=1.0.1 (from paramiko<3.0.0,>=2.7.1->python-gvm<21.0,>=1.4->gvm-tools)
  Using cached https://files.pythonhosted.org/packages/9d/57/2f5e6226a674b2bcb6db531e8b383079b678df5b10cdaa610d6cf20d77ba/PyNaCl-1.4.0-cp35-abi3-manylinux1_x86_64.whl
Collecting cryptography>=2.5 (from paramiko<3.0.0,>=2.7.1->python-gvm<21.0,>=1.4->gvm-tools)
  Using cached https://files.pythonhosted.org/packages/08/31/c43f1e45b4a5ebac13ff038a3f167ba3c7432f6dc8683ea504f5af9265eb/cryptography-3.2.1-cp35-abi3-manylinux1_x86_64.whl
Collecting bcrypt>=3.1.3 (from paramiko<3.0.0,>=2.7.1->python-gvm<21.0,>=1.4->gvm-tools)
  Using cached https://files.pythonhosted.org/packages/52/a7/51ab6481ac355517696477889d8ab232106a0ddadda642c54e47a2ab40b9/bcrypt-3.2.0-cp36-abi3-manylinux1_x86_64.whl
Collecting six (from pynacl>=1.0.1->paramiko<3.0.0,>=2.7.1->python-gvm<21.0,>=1.4->gvm-tools)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting cffi>=1.4.1 (from pynacl>=1.0.1->paramiko<3.0.0,>=2.7.1->python-gvm<21.0,>=1.4->gvm-tools)
  Using cached https://files.pythonhosted.org/packages/50/ca/bbca0fd95b24a1d4f0d2e016f09f35ae68d4fe72bf34cc538d0a0d2d3e10/cffi-1.14.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting pycparser (from cffi>=1.4.1->pynacl>=1.0.1->paramiko<3.0.0,>=2.7.1->python-gvm<21.0,>=1.4->gvm-tools)
  Using cached https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl
Installing collected packages: six, pycparser, cffi, pynacl, cryptography, bcrypt, paramiko, defusedxml, lxml, python-gvm, gvm-tools
Successfully installed bcrypt-3.2.0 cffi-1.14.3 cryptography-3.2.1 defusedxml-0.6.0 gvm-tools-20.10.1 lxml-4.6.1 paramiko-2.7.2 pycparser-2.20 pynacl-1.4.0 python-gvm-20.11.0 six-1.15.0
**bhagyashree@bhagyashree-Inspiron-3521:~$ python3 -m pip install -e gvm-tools**
Directory 'gvm-tools' is not installable. File 'setup.py' not found.
**bhagyashree@bhagyashree-Inspiron-3521:~$** 

Can someone please help me in solving this

**Comment by y0urself** [comment]
https://github.com/greenbone/gvm-tools/pull/246

**Comment by bjoernricks** [comment]
Please only create questions at our community forum. Only create issues here if you get tracebacks during actually **using** our software. Not during installation and setup.
