### ISSUE TITLE
Missing tag in CHANGELOG.md

### ISSUE THREAD

**Issue by albert-github** [greenbone/gvm-tools#371]
### Current behavior
In the changelog for version 20.10.0 we have the line:
```
- Fixed `send-schedule.gmp.py` script, because <timezone_abbrev> has been [removed](https://github.com/greenbone/gvmd/commit/d4a0fa2287b425199330b7e5671b61cdbd836fe4) from Schedules, using <timezone> instead. [#299]
```
and we see:
- Fixed `send-schedule.gmp.py` script, because <timezone_abbrev> has been [removed](https://github.com/greenbone/gvmd/commit/d4a0fa2287b425199330b7e5671b61cdbd836fe4) from Schedules, using <timezone> instead. [#299]

so missing `<timezone>` 

### Expected behavior

```
- Fixed `send-schedule.gmp.py` script, because `<timezone_abbrev>` has been [removed](https://github.com/greenbone/gvmd/commit/d4a0fa2287b425199330b7e5671b61cdbd836fe4) from Schedules, using `<timezone>` instead. [#299]
```
which gives
- Fixed `send-schedule.gmp.py` script, because `<timezone_abbrev>` has been [removed](https://github.com/greenbone/gvmd/commit/d4a0fa2287b425199330b7e5671b61cdbd836fe4) from Schedules, using `<timezone>` instead. [#299]

### GVM versions
Current release.

**Comment by y0urself** [comment]
So you can provide an PR for this?

**Comment by y0urself** [comment]
I have changed it in the release notes.
