### ISSUE TITLE
Correct XML encoding for commands

### ISSUE THREAD

**Issue by BaaaZen** [greenbone/gvm-tools#40]
The API has a serious problem with creating the commands. You always concatenate strings with the XML tags, but you never encode the values. This works as long as you don't use any XML specific characters. I got a problem when I tried to create a task with an ampersand (&) in the name. So you should always encode all inserted strings!

I fixed the problem for the "createTaskCommand" on a clean way, as I only had the problem with that command. Maybe you could fix all the other commands, too?

First fix: https://github.com/greenbone/gvm-tools/pull/39

**Comment by jjnicola** [comment]
PR #62 fix the problem in the same way for all command methods.
