### ISSUE TITLE
How to delete a  scan result by command line or python script?

### ISSUE THREAD

**Issue by yldiscover** [greenbone/gvm-tools#404]
Hi,
  Do u know how to delete a  scan result by command line or python script?
  I know delete_report, but there is no delete_result .

**Comment by cfi-gb** [comment]
This is a bug tracker so i'm closing this issue as invalid.

Please ask such questions at https://community.greenbone.net/c/gmp/11.

Thanks for your understanding and for helping to keep the community channels clean (bug reports here, questions at the community portal).
