### ISSUE TITLE
Why get_reports in command line only return 10 reports?

### ISSUE THREAD

**Issue by yldiscover** [greenbone/gvm-tools#405]
Hi,
  There are more than 10 results in the system,but the get_reports command only got 10 of them. 
  Do u know how to get all the reports by command line ?

  Thanks.

**Comment by cfi-gb** [comment]
This is a bug tracker so i'm closing this issue as invalid.

Please ask such questions at https://community.greenbone.net/c/gmp/11.

Thanks for your understanding and for helping to keep the community channels clean (bug reports here, questions at the community portal).
