### ISSUE TITLE
Unexpected byte and multiple xml in the gvm-cli output

### ISSUE THREAD

**Issue by hoboristi** [greenbone/gvm-tools#471]
### Expected behavior
Do not have 'b' at the cli's response, also only one multiline xml given.

### Current behavior
There is an unexpexted byte in the output of gvm-cli (below the '**b**' char)
Also there is 2 xml (1 per line), compared to older releases

```
b'<authenticate_response status="200" status_text="OK"><role>Super Admin</role><timezone>UTC</timezone></authenticate_response>'
<get_version_response status="200" status_text="OK"><version>21.4</version></get_version_response>
```

The error seems to be located at `/usr/local/lib/python3.7/dist-packages/gvm/utils.py` (gvm-tools installed by pip)

If I remove `<authenticate_response`, seems to be OK.

### Steps to reproduce
1. `pip install gvm-tools`
2. `/usr/local/bin/gvm-cli --gmp-username=admin --gmp-password=pass --protocol=GMP socket`
3. Response: 
```
b'<authenticate_response status="200" status_text="OK"><role>Super Admin</role><timezone>UTC</timezone></authenticate_response>'
<get_version_response status="200" status_text="OK"><version>21.4</version></get_version_response>

```
### GVM versions
**gsa:** (gsad --version)

**gvm:** (gvmd --version)

**openvas-scanner:** (openvassd --version)

**gvm-libs:**

**gvm-tools:** (gvm-cli --version)
gvm-cli 21.1.0 (API version 21.5.0)

### Environment
**Operating system:**

**Installation method / source:** (packages, source installation)

### Logfiles

```

```

**Comment by y0urself** [comment]
I guess I just missed removing a debug print statement in `python-gvm`.

**Comment by y0urself** [comment]
Using https://github.com/greenbone/python-gvm/releases/tag/v21.6.0 should fix this. :)
