### ISSUE TITLE
[22.6.0] files missing in tar package

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gvm-tools#704]
The the tar ball, the files:
[poetry.lock](https://github.com/greenbone/gvm-tools/blob/main/poetry.lock)
[poetry.toml](https://github.com/greenbone/gvm-tools/blob/main/poetry.toml)
[pyproject.toml](https://github.com/greenbone/gvm-tools/blob/main/pyproject.toml)
are missing

**Comment by y0urself** [comment]
can not confirm.

**Comment by tuxmaster5000** [comment]
LANG=C gpg2 --keyring=SOURCES/GBCommunitySigningKey.asc --verify SOURCES/gvm-tools-22.6.0.tar.gz.asc SOURCES/gvm-tools-22.6.0.tar.gz
gpg: Signature made Thu Jun 16 13:05:34 2022 CEST
gpg:                using RSA key 8AE4BE429B60A59B311C2E739823FAA60ED1E580
gpg: Good signature from "Greenbone Community Feed integrity key" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 8AE4 BE42 9B60 A59B 311C  2E73 9823 FAA6 0ED1 E580


tar -tzf SOURCES/gvm-tools-22.6.0.tar.gz
gvm-tools-22.6.0/
gvm-tools-22.6.0/.bandit
gvm-tools-22.6.0/.coveragerc
gvm-tools-22.6.0/.github/
gvm-tools-22.6.0/.github/CODEOWNERS
gvm-tools-22.6.0/.github/ISSUE_TEMPLATE.md
gvm-tools-22.6.0/.github/PULL_REQUEST_TEMPLATE.md
gvm-tools-22.6.0/.github/dependabot.yml
gvm-tools-22.6.0/.github/workflows/
gvm-tools-22.6.0/.github/workflows/ci-python.yml
gvm-tools-22.6.0/.github/workflows/codeql-analysis-python.yml
gvm-tools-22.6.0/.github/workflows/deploy-pypi.yml
gvm-tools-22.6.0/.github/workflows/release-pontos-manually.yml
gvm-tools-22.6.0/.github/workflows/release-pontos.yml
gvm-tools-22.6.0/.gitignore
gvm-tools-22.6.0/.pylintrc
gvm-tools-22.6.0/CHANGELOG.md
gvm-tools-22.6.0/LICENSE
gvm-tools-22.6.0/MANIFEST.in
gvm-tools-22.6.0/README.md
gvm-tools-22.6.0/RELEASE.md
gvm-tools-22.6.0/changelog.toml
gvm-tools-22.6.0/changelog/
gvm-tools-22.6.0/changelog/v21.10.0.md
gvm-tools-22.6.0/changelog/v22.6.0.md
gvm-tools-22.6.0/docs/
gvm-tools-22.6.0/docs/Makefile
gvm-tools-22.6.0/docs/_static/
gvm-tools-22.6.0/docs/_static/custom.css
gvm-tools-22.6.0/docs/_static/greenbone.png
gvm-tools-22.6.0/docs/_templates/
gvm-tools-22.6.0/docs/_templates/sidebarlogo.html
gvm-tools-22.6.0/docs/conf.py
gvm-tools-22.6.0/docs/config.rst
gvm-tools-22.6.0/docs/connectiontypes.rst
gvm-tools-22.6.0/docs/favicon.gif
gvm-tools-22.6.0/docs/glossary.rst
gvm-tools-22.6.0/docs/index.rst
gvm-tools-22.6.0/docs/install.rst
gvm-tools-22.6.0/docs/requirements.txt
gvm-tools-22.6.0/docs/scripting.rst
gvm-tools-22.6.0/docs/tools.rst
gvm-tools-22.6.0/gvmtools/
gvm-tools-22.6.0/gvmtools/__init__.py
gvm-tools-22.6.0/gvmtools/__version__.py
gvm-tools-22.6.0/gvmtools/cli.py
gvm-tools-22.6.0/gvmtools/config.py
gvm-tools-22.6.0/gvmtools/helper.py
gvm-tools-22.6.0/gvmtools/parser.py
gvm-tools-22.6.0/gvmtools/pyshell.py
gvm-tools-22.6.0/gvmtools/script.py
gvm-tools-22.6.0/poetry.lock
gvm-tools-22.6.0/poetry.toml
gvm-tools-22.6.0/pyproject.toml
gvm-tools-22.6.0/scripts/
gvm-tools-22.6.0/scripts/.pylintrc
gvm-tools-22.6.0/scripts/README.md
gvm-tools-22.6.0/scripts/application-detection.gmp.py
gvm-tools-22.6.0/scripts/bulk-modify-schedules.gmp.py
gvm-tools-22.6.0/scripts/cfg-gen-for-certs.gmp.py
gvm-tools-22.6.0/scripts/check-gmp.gmp.py
gvm-tools-22.6.0/scripts/clean-sensor.gmp.py
gvm-tools-22.6.0/scripts/combine-reports.gmp.py
gvm-tools-22.6.0/scripts/create-consolidated-report.gmp.py
gvm-tools-22.6.0/scripts/create-cve-report-from-json.gmp.py
gvm-tools-22.6.0/scripts/create-dummy-data.gmp.py
gvm-tools-22.6.0/scripts/create-targets-from-host-list.gmp.py
gvm-tools-22.6.0/scripts/default_report_data.json
gvm-tools-22.6.0/scripts/delete-overrides-by-filter.gmp.py
gvm-tools-22.6.0/scripts/export-pdf-report.gmp.py
gvm-tools-22.6.0/scripts/generate-random-reports.gmp.py
gvm-tools-22.6.0/scripts/generate-random-targets.gmp.py
gvm-tools-22.6.0/scripts/list-tasks.gmp.py
gvm-tools-22.6.0/scripts/monthly-report-gos4.gmp.py
gvm-tools-22.6.0/scripts/monthly-report.gmp.py
gvm-tools-22.6.0/scripts/nvt-scan.gmp.py
gvm-tools-22.6.0/scripts/requirements.txt
gvm-tools-22.6.0/scripts/scan-new-system.gmp.py
gvm-tools-22.6.0/scripts/send-delta-emails.gmp.py
gvm-tools-22.6.0/scripts/send-schedules.gmp.py
gvm-tools-22.6.0/scripts/send-targets.gmp.py
gvm-tools-22.6.0/scripts/send-tasks.gmp.py
gvm-tools-22.6.0/scripts/start-alert-scan.gmp.py
gvm-tools-22.6.0/scripts/start-multiple-alerts-scan.gmp.py
gvm-tools-22.6.0/scripts/start-nvt-scan.gmp.py
gvm-tools-22.6.0/scripts/sync-hosts.gmp.py
gvm-tools-22.6.0/scripts/update-task-target.gmp.py
gvm-tools-22.6.0/tests/
gvm-tools-22.6.0/tests/__init__.py
gvm-tools-22.6.0/tests/root_help.snap
gvm-tools-22.6.0/tests/scripts/
gvm-tools-22.6.0/tests/scripts/__init__.py
gvm-tools-22.6.0/tests/scripts/example_schedules.xml
gvm-tools-22.6.0/tests/scripts/example_target.xml
gvm-tools-22.6.0/tests/scripts/example_task.xml
gvm-tools-22.6.0/tests/scripts/get_alerts.xml
gvm-tools-22.6.0/tests/scripts/get_scan_configs.xml
gvm-tools-22.6.0/tests/scripts/invalid_xml.xml
gvm-tools-22.6.0/tests/scripts/test_combine_reports.py
gvm-tools-22.6.0/tests/scripts/test_create_consolidated_report.py
gvm-tools-22.6.0/tests/scripts/test_send_schedules.py
gvm-tools-22.6.0/tests/scripts/test_send_targets.py
gvm-tools-22.6.0/tests/scripts/test_send_tasks.py
gvm-tools-22.6.0/tests/scripts/test_start_alert_scan.py
gvm-tools-22.6.0/tests/socket_help.snap
gvm-tools-22.6.0/tests/ssh_help.snap
gvm-tools-22.6.0/tests/test.cfg
gvm-tools-22.6.0/tests/test_auth.cfg
gvm-tools-22.6.0/tests/test_config.py
gvm-tools-22.6.0/tests/test_helper.py
gvm-tools-22.6.0/tests/test_parser.py
gvm-tools-22.6.0/tests/tls_help.snap

**Comment by y0urself** [comment]
So what are 
```
gvm-tools-22.6.0/poetry.lock
gvm-tools-22.6.0/poetry.toml
gvm-tools-22.6.0/pyproject.toml
```
?!

**Comment by tuxmaster5000** [comment]
Very strange the build tool will report:
ERROR: tox config file (either pyproject.toml, tox.ini, setup.cfg) not found

I will take a deeper look into it, because the previous versions runs out of the box.

**Comment by y0urself** [comment]
How are you building?
