### ISSUE TITLE
Variable re-assignments in gmp.py 

### ISSUE THREAD

**Issue by wiegandm** [greenbone/gvm-tools#73]
There are multiple instances in gmp.py where variables are immediately re-
assigned, likely in error. The instances look like the assignment should go to
an object of the variable instead of the variable itself. For example, the
following code

https://github.com/greenbone/gvm-tools/blob/6d293e66b8971273b23cda8193cb87f838899900/gmp/gmp.py#L89-L90

should probably read

```
_xmlMethods = etree.SubElement(xmlRoot, 'method')
_xmlMethods.text = method[0]
```

Other instances:

https://github.com/greenbone/gvm-tools/blob/6d293e66b8971273b23cda8193cb87f838899900/gmp/gmp.py#L101-L102

https://github.com/greenbone/gvm-tools/blob/6d293e66b8971273b23cda8193cb87f838899900/gmp/gmp.py#L105-L106

**Comment by jjnicola** [comment]
Fixed with PR #74
