### ISSUE TITLE
problems with gmp.get_version()

### ISSUE THREAD

**Issue by lgbff** [greenbone/gvm-tools#75]
are gvm-tools run with alle gmp version hosts?
I try gmp.get_version() with version 6.0 and the anser is: 
gmp.gvm_connection.GMPError: Bogus command name

**Comment by bjoernricks** [comment]
All our software **should** run against supported version. Currently this is only OpenVAS 9 with openvas-manager 7. OpenVAS 8 has reached end of life and if you are still using it please upgrade to version 9.

**Comment by lgbff** [comment]
ok, i use the Version from Debian stable....
